### ISSUE TITLE
Render highways from OSM data

### ISSUE THREAD

**Issue by jumbanho** [chadrockey/TGC-Designer-Tools#42]
Many golf courses have streets/roads and corresponding sidewalks and paths running through them.  Some people have been changing them to golf carts to get them to render in TGC.  That activity should be discouraged in the OSM realm, but adding these important features in the program would remove that incentive to mismap in OSM

**Comment by chadrockey** [comment]
The game wouldn't render these how you wanted in game.  There's only a few surface types and they only get so wide.  It's best for this to be done by hand in the final designer.

I also wouldn't render streets and roads because their waypoints exist outside out of the course bounds and that's not a technical problem I'm interested in solving.
https://github.com/chadrockey/TGC-Designer-Tools/blob/master/OSMTGC.py#L421

Sorry for the mess on OSM, if I did a version two of this problem I would probably have users map locally on their computer to keep your community cleaner.

**Comment by jumbanho** [comment]
Ok, sorry to bother you!

**Comment by chadrockey** [comment]
Not bothered at all, feel free to submit a PR if you can come up with a
solution that mitigates untrained OSM editors and highways.
