### ISSUE TITLE
Problem with tgc_gui

### ISSUE THREAD

**Issue by cjyaniger** [chadrockey/TGC-Designer-Tools#54]
I am new to TGC 2019, and am trying to create my local course on designer. I have successfully downloaded the LiDAR  .las and .xml files from NOAA for Pine Ridge Golf Course in Lutherville, MD. I found that this course has already been fairly well detailed on Open Street Maps, as shown in the first attached picture. As shown, it includes all tees, fairways, greens and bunkers. It shows all cart paths, streets and parking lots, and has boundary lines between the course and the water reservoir(highlighted in photo) but does not seem to have water hazard areas. 
![721AD786-0BA6-44E7-8213-F2E7CFD4F012](https://user-images.githubusercontent.com/69204664/90534167-67e1cb80-e147-11ea-8ce5-c412a08e043f.png)

Opened tgc_gui, rev 3.2, and was able to generate a .course file, which Included the full 18-hole layout (including all tees, fairways, greens and bunkers), correct terrain elevations, and exclusion of all masked areas. 

However, several things did not work properly. First, although the masked areas were excluded, they did not show up as black areas in the 2-D preview as shown in the following two photos. 
![49EDF9A0-D072-46D3-9891-FA91A97BD3F8](https://user-images.githubusercontent.com/69204664/90535670-2a7e3d80-e149-11ea-8e04-7aa413a2a71c.jpeg)
![8C0221E8-D6D0-4443-B35F-7BBB274FA8A1](https://user-images.githubusercontent.com/69204664/90535678-2d792e00-e149-11ea-9253-2817b22d29c3.jpeg)

Second, although the final course file did exclude the masked areas, the edges were sharp jagged cliffs, and not smoothed as they should have been as shown in the photo below. 
![1744785E-2CC3-4244-8998-ACCF1B049022](https://user-images.githubusercontent.com/69204664/90537248-1c312100-e14b-11ea-8a64-d7918c92f00a.jpeg)

![5B7B85EF-F308-43BE-BCCA-A9886C987905](https://user-images.githubusercontent.com/69204664/90536226-c3ad5400-e149-11ea-8e10-d316f00bea6c.jpeg)

Third, although the tgc_gui screen showed that the heights of all the trees were collected, and the boxes for “add trees from LiDAR” and “tree variety” were checked during the “select and import Heightmap and OSM into course”, no trees were included in the 2-D preview or the final .course file, as shown below. 
![71ADE531-BACF-46F8-B85C-2B635C1DE7E4](https://user-images.githubusercontent.com/69204664/90537537-70d49c00-e14b-11ea-8fa7-d52cc339ce42.jpeg)

I did make an earlier run where I had not checked these boxes, but checked “import mapped woods/trees” under the OSM column, and they appeared as grey, flat areas. 

Finally, none of the cart paths, streets or parking lots appeared, even though they are in the OSM FILE. 

As I said, this is my first venture into TGC Designer, and any help wold be greatly appreciated.

**Comment by chadrockey** [comment]
The background terrain checkbox is why you see the edges and terrain expanding beyond the area you painted in red.  It's a crutch for those not comfortable using the sculpting tools to fill in unplayable but visible areas.

Your lidar data might not have included vegetation data, so you probably won't get lidar trees.  I know it goes through and really looks hard for "trees", but they are probably bumps on the ground even if it says detected 45,000 trees.  If the detected bumps aren't 2.0m or taller we call them trees, but we don't plant a tree in game.  The grey marked areas are "woods" from OSM that are a placeholder for you to plant trees in game.  I can't efficiently plant trees for you, it's to protect the planting meter.

Are the cartpaths marked as "golf: cartpath" in OSM?  If they are not, then they won't import.  I don't usually import streets or parking lots because they don't look great and you have to spline them by hand/it's one of the easier things since they are large and don't affect playability.
