### ISSUE TITLE
Water hazards show up as huge craters.  There is no water at all

### ISSUE THREAD

**Issue by kevinkorb** [chadrockey/TGC-Designer-Tools#63]
I assume this is due to some calculation off in the heightmaps, and the height of the course is higher than the water table therefor there is no water?

I see in the console: Shifting elevation by: -126.3499984741211, maybe that has something to do with it?

Thank you!

**Comment by kevinkorb** [comment]
After playing with the elevation, seems like that is not the way to go.  I was able to go back and fill in the water manually.  I'm sure you never expected this to be the final step to course designing, so this obviously isn't a huge issue, but unexpected (and fixable) on my end.  The tool is really awesome btw.  Thank you.

**Comment by Phenrik1** [comment]
That is what it has always been. The game or generator has never ever
filled up the water. That is your job..


tir. 22. des. 2020, 16:37 skrev Kevin Korb <notifications@github.com>:

**Comment by chadrockey** [comment]
@kevinkorb I never *wanted* this to be the final step to course designing, but the water features in game are too primitive and they warp/effect the features around them.  Because of this I was never able to automate the water planting so the best I can do is drop some mulch to help you line it up by hand.

Unfortunately, this means the learning curve goes from basically flat to one of the hardest aspects of the designer immediately.  :\
