### ISSUE TITLE
LIDAR import course high above water table

### ISSUE THREAD

**Issue by MBUA2309** [chadrockey/TGC-Designer-Tools#66]
I imported my local course following the directions from Chad. My course is elevated all along the periphery by about 60 ft above the surrounding area. The water hazards are all empty on the course I can't get the water table to rise to the necessary height to fill water on the course. Please see attached pictures any recommendation would be appreciated. 
![16109730018264223805689614118553](https://user-images.githubusercontent.com/77621289/104915686-02487400-595f-11eb-80f0-1224cc3b7b55.jpg)
![16109730198912710975734342816955](https://user-images.githubusercontent.com/77621289/104915742-15f3da80-595f-11eb-985b-18d164e1e7eb.jpg)
![16109730585478877876523236595820](https://user-images.githubusercontent.com/77621289/104915780-2310c980-595f-11eb-92b9-8c6006c70c66.jpg)

**Comment by chadrockey** [comment]
Hi @MBUA2309 the "water table" is an old concept from The Golf Club 1 and is no longer used by anyone with a brain.

Many/most golf courses have man-made water features, so it's not like there is a "flat" level where all water on a course can exist.

What you're seeing is the intended hand-off point from the tool to you, the designer.  The edges of the courses can be masked (if they are visible) by using the red terrain tool.  Unfortunately there's some learning of the feature there, but RED can't affect the lidar so you'll be able to correct the edges nicely.

As for the water features, I can't automate this because the game now uses flat rectangular sheets of water.  These drastically affect the terrain and splines near the water so I can't place them for you.  The best I can do is drop some mulch to help you with the outline of the water.  You should delete the mulch right after you plant the water.  A little bit of time with Crazy Canuck's tutorials and you'll have this course looking great from here.
