### ISSUE TITLE
LAS files taking a long time

### ISSUE THREAD

**Issue by shots74** [chadrockey/TGC-Designer-Tools#69]
While in the golf tool designer and the course is being built off the .las files and .xml files, this process takes a very long time, days even.  A whole day has gone by and out of 7,000 files, this application has only gone through 500 files, why is this taking so long to complete?

**Comment by chadrockey** [comment]
7000 is probably too many files.....  I think you’re trying to process data for a whole county, state, or country.

How many MB is the data?  You can use at most 1/2 of raw data as your computer has RAM.

**Comment by shots74** [comment]
The date that was extracted was about a terabyte.  I am trying to created Glen Brook Golf Club in Stroudsburg PA. and following the process, these are the files that were provided.

**Comment by chadrockey** [comment]
I can’t provide specific support for narrowing down the files, but that’s about 1000 times too much data.  I would use 200MB to 1GB at most.

There should be some key or guide on how to narrow the files down by number or name.  Otherwise, try one file at a time to verify the process is running and narrow it down.
