### ISSUE TITLE
LAZ file will not load

### ISSUE THREAD

**Issue by kaptinenny14** [chadrockey/TGC-Designer-Tools#96]
Tried this multiple times but get the same issue. This is UK Lidar data Point Cloud at 1m resolution. I have tried the lower resolution with similar results.  The course runs over 2 grid locations and the sister location (NY7015_P_10645_20210112_20210406.laz) loads fine. I realise that others have suggested converting to LAS but every other course I have done has used this format without problems.

This pasted from TCG Golf Tools 0.3.2
**Could not load NY7020_P_10645_20210112_20210406.laz Please report this issue.**

**Comment by chadrockey** [comment]
@kaptinenny14 the laz format is a compressed, better use of bandwidth and diskspace lidar format.

Unfortunately, it's still being finalized and sometimes people get it wrong or they use a version too new for us to support.  It sounds like it could be the case here since neighboring areas work well.

Have you tried the suggestion from #70  to use lastools to convert?

We also rely on the really great laspy project, but they've been very busy updating things that it's difficult to keep up with the changes and make sure we don't break anything here:
https://github.com/laspy/laspy/blob/master/CHANGELOG.md

Your best bet would be to find a way to upload the problematic laz file to dropbox or google drive so that everyone can take a look and see what the issue is.

**Comment by kaptinenny14** [comment]
@chadrockey Thanks very much for the explantion. Duely converted to LAS and everything worked perfectly. Your help is very much appreciated.
